237 typeerror   init   missing 1 required positional argument action dim (#239)
* fix bug and GPU Vectorized Env

* GPU Vec Env Fix bug

* Add ArgumentParser for VecEnv

* setup.py

* fix bug in Evaluator